---
- hosts: all
  tasks:

  - name: print debug message
    debug: msg="ansible is working"

  - name: copy over revashare nginx config
    copy:
      src: ./revashare_site
      dest: /etc/nginx/sites-enabled/revashare_site
      owner: root
      group: root
      mode: 0644
    notify: 
      - reload nginx

  - name: copy webapp
    copy:
      src: ../public/
      dest: /usr/share/nginx/sites/revashare
      owner: david
      group: david
    notify:
     - reload nginx

  handlers:
    - name: reload nginx
      service: name=nginx state=restarted
      sudo: yes


  roles:
    - { role: geerlingguy.nginx }
